version: '3.1'

services:
  db:
    container_name: nlw_db
    image: postgres
    restart: on-failure
    ports:
      - 5433:5432
    volumes:
      - .docker/volumes/db:/var/lib/postgres
    environment:
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_ROOT_PASSWORD: root1234
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: nlw_adminer
    restart: on-failure
    ports:
      - 8081:8080
    environment:
      ADMINER_DEFAULT_SERVER: nlw_db
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
    driver: bridge